#pragma once

enum eNUAPI_PROJECT {
    PROJECT_INVALID = -1,
    PROJECT_UNKNOWN_0 = 0,
    PROJECT_HOBBIT_SUB = 1,
    PROJECT_TTANIMATION = 2,
    PROJECT_LEGO_HARRY_POTTER = 3,
    PROJECT_LEGO_CLONE_WARS = 4,
    PROJECT_LEGO_CITY = 5,
    PROJECT_LEGO_PIRATES = 6,
    PROJECT_LEGO_HARRY_POTTER_2 = 7,
    PROJECT_WHATS_YOUR_NEWS = 8,
    PROJECT_SCENE_VIEWER = 9,
    PROJECT_LEGO_SUPER_HEROES_1 = 10,
    PROJECT_LEGO_BATMAN_MOVIE = 11,
    PROJECT_LEGO_BATMAN_2_SHORTS = 12,
    PROJECT_LEGO_LOTR = 13,
    PROJECT_LEGO_MARVEL = 14,
    PROJECT_LEGO_EMMET = 15,
    PROJECT_LEGO_CHIMA = 16,
    PROJECT_UNKNOWN_17 = 17,
    PROJECT_BUILDER_GAME = 18,
    PROJECT_LEGO_HOBBIT = 19,
    PROJECT_UNKNOWN_20 = 20,
    PROJECT_LEGO_ORANGE = 21,
    PROJECT_LEGO_GREEN = 22,
    PROJECT_UNKNOWN_23 = 23,
    PROJECT_COUNT = 24
};

unsigned int NU2APIIsLegoProject();
eNUAPI_PROJECT NU2APIGetProject(bool param_1);
unsigned int NU2APIIsHQRenderProject();
void NU2APISetProject(eNUAPI_PROJECT project);
char* NU2APIGetProjectName(eNUAPI_PROJECT project);
char* NU2APIGetCurrentProjectName();
eNUAPI_PROJECT NU2APIGetProjectFromName(const char* name);
int NU2APIVersionString(char* buffer, int buffer_size);
